### ISSUE TITLE
Revert camera change please

### ISSUE THREAD

**Issue by ABNTGeneric** [pseudopulse/PlayableDoomguy#5]
Being low to the ground was much better, now he feels 20 feet tall. Also, please make it so the camera turns rather than orbits. It's incredibly annoying to make jumps or judge your position in relation to enemies, and it's disorienting to aim.

Overall very fun, thanks for making.

**Comment by MagentaLizard** [comment]
Being tall and the orbiting camera does feel super weird

**Comment by pseudopulse** [comment]
reverted in 1.1.1
